[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# 1) Ensure asset requests are never rewritten to index.html.
#    If an asset doesn't exist (old hashed file), return 404 instead of HTML.
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# 2) Pass-through for other top-level static files (optional safety).
[[redirects]]
  from = "/:file.:ext"
  to = "/:file.:ext"
  status = 200

# 3) SPA fallback for all other routes.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Strong caching for versioned build assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

# Keep HTML fresh so it always points to current chunk names
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"
