[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Note: We're using _redirects file instead of netlify.toml redirects
# to avoid conflicts. This file only contains build configuration.
