[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/functions/v1/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = { "path" = "!^/functions/v1/.*" }

[build.environment]
  NODE_VERSION = "18"