[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Serve static assets first, then fallback to SPA
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
