[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/functions/v1/*"
  to = "/.netlify/functions/v1/:splat"
  status = 200

[[redirects]]
  from = "/auth/callback"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"